version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    networks:
      - my-network

  node-app:
    build: ../node-app
    container_name: node-app
    entrypoint: dockerize -wait tcp://mysql-db:3306 -timeout 20s npm start
    volumes:
      - ./dist:/usr/src/dist
    depends_on:
      - mysql-db
    networks:
      - my-network

  mysql-db:
    image: mysql:5.7
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fullcycle
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql-data: